app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# SonataAdminBundle importando configuracion rutas
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin